### ISSUE TITLE
Doesn't work on full .NET Framework anymore (targets netcoreapp2.0)

### ISSUE THREAD

**Issue by wagich** [CadyIO/hangfire-ravendb#24]
Is there a specific reason for targetting `netcoreapp2.0` instead of `netstandard2.0` which, as I understand it, is recommended for libraries?

If not, it would be nice to switch to targetting `netstandard2.0` since that is "implemented" in the full .NET Framework from version 4.6.1, enabling the same assembly to be used from both .NET Core and the full framework.

**Comment by AustinWinstanley** [comment]
No, this was an oversight because I wasn't paying attention. Switching to netstandard2.0 and will have an update out shortly. Thanks.

**Comment by AustinWinstanley** [comment]
There is a new Release 3.1.1 that targets netstandard2.0
