### ISSUE TITLE
RavenDB dependency issue on full framework

### ISSUE THREAD

**Issue by dweggemans** [CadyIO/hangfire-ravendb#25]
I am trying to use hangfire.ravendb in a .net 4.6 project that also uses RavenDB. This is not possible due to a version conflict with RavenDB client. I am using the net45 version, while this library is using the netstandard1.3 version. 

The netstandard1.3 dependency doesn't resolve due to difference in public key token (netstandard1.3's key is null). I've tried to get around this by manually loading the full version assembly using AppDomain.CurrentDomain.AssemblyResolve event but that didn't work either due to implementation differences between the assembly versions.

Could you provide a full framework version or workaround?

**Comment by AustinWinstanley** [comment]
Added support for DotNet 4.5, 4.6, NetStandard 1.3, 1.4, 1.5,1.6 and added new sample console project for DotNet 4.6 in new version 3.2.0.

https://github.com/CadyIO/hangfire-ravendb/releases/tag/3.2.0
